config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  # Users
  resources :users

  # Sessions
  resources :user_sessions
  get 'login', to: 'user_sessions#new', :as => :login
  post 'logout', to: 'user_sessions#destroy', :as => :logout

  # Decks
  resources :decks

  # Cards
  resources :cards
  post 'revision_card' => 'cards#revision_card'

  # Oauth
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/card.rb
class Card < ActiveRecord::Base
  mount_uploader :card_image, CardImageUploader

  belongs_to :user
  belongs_to :deck

  validates :original_text, :translated_text, :review_date, :deck_id, presence: true
  before_validation :original_equal_translated
  before_validation :set_review_date, on: [:create]

  scope :random, -> { order("RANDOM()").limit(1) }
  scope :revision, -> { where("review_date <= ?", Time.zone.now) }

  def check_answer(answer)
    words_eq(original_text, answer).tap do |success|
      update_review_date(success ? attempt : 0)
    end
  end

  private
  def original_equal_translated
    if words_eq(original_text, translated_text)
      errors.add(:translated_text, "translated text needs not be equal to original text")
    end
  end

  def update_review_date(attempt)
    review_date = Time.zone.now + add_time(attempt)
    update_attributes(review_date: review_date, attempt: attempt + 1)
  end

  def add_time(attempt)
    case attempt
      when 0..1
        12.hour
      when 2
        3.day
      when 3
        7.day
      when 4
        2.week
      else
        1.month
    end
  end

  def words_eq(first, second)
    first_word = first.downcase.strip
    second_word = second.downcase.strip

    levenshtein_distance(first_word, second_word) < 1
  end

  def set_review_date
    self.review_date = Time.zone.now
  end

  def levenshtein_distance(original, translated)
    DamerauLevenshtein.distance(original, translated)
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :cards

  validates :title, presence: true

  scope :current, -> { where("current", true) }

  before_save :update_current_status

  private
  def update_current_status
    user.decks.update_all(current: false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  has_many :cards
  has_many :decks

  validates :email, :password, :password_confirmation, presence: true
  validates :email, uniqueness: true
  validates :password, confirmation: true, length: { minimum: 3 }

  accepts_nested_attributes_for :authentications

  # For cron/mailer
  def self.pending_cards
    User.joins(:cards).where('cards.review_date <= ?', Time.zone.now).each do |user|
      NotificationMailer.pending_cards(user).deliver_now
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include HttpAcceptLanguage::AutoLocale

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login, :set_locale

  private
  def not_authenticated
    redirect_to login_path
  end

  def set_locale
    if current_user && current_user.locale.present?
      I18n.locale = current_user.locale || I18n.default_locale
    else
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :decks, only: [:edit, :update, :new, :create]

  def index
    @cards = current_user.cards.order(:review_date)
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])

    if @card.update_attributes(card_params)
      redirect_to cards_path
    else
      render 'edit'
    end
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.create(card_params)

    if @card.valid?
      redirect_to cards_path
    else
      render 'new'
    end
  end

  def destroy
    Card.find(params[:id]).destroy
    redirect_to cards_path
  end

  def revision_card
    @card = Card.find(params[:card][:id])
    @answer = params[:answer]

    if @card.check_answer(params[:answer])
      redirect_to root_path, flash: { success: "Правильно" }
    else
      flash.now[:warning] = "Не правильно"
      render '_right_answer'
    end
  end

  private
  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :card_image, :deck_id, :user_id)
  end

  def decks
    @decks = current_user.decks
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :deck, only: [:show, :edit, :update]

  def index
    @decks = current_user.decks.order(:id)
  end

  def show
  end

  def edit
  end

  def update
    if @deck.update_attributes(deck_params)
      redirect_to decks_path, flash: { success: 'Колода обновлена' }
    else
      flash.now[:warning] = 'Ай-яй'
      render 'edit'
    end
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)

    if @deck.save
      redirect_to decks_path, flash: { success: 'Колода создана' }
    else
      flash.now[:warning] = 'Ай-яй'
       render 'new'
    end
  end

  def destroy
    current_user.decks.find(params[:id]).destroy
    redirect_to decks_path, flash: { success: 'Колода удалена' }
  end

  private
  def deck_params
    params.require(:deck).permit(:title, :current, :user_id)
  end

  def deck
    @deck = current_user.decks.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if current_user.decks.current.any?
      @deck = current_user.decks.current.take
      @revision_card = @deck.cards.revision.random.take
    else
      @revision_card = current_user.cards.revision.random.take
    end
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_filter :require_login

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, flash: { success: "Logged in from #{provider.titleize}!" }
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, flash: { success: "Logged in from #{provider.titleize}!" }
      rescue
        redirect_to root_path, flash: { warning: "Failed to login from #{provider.titleize}!" }
      end
    end
  end

  private
  def auth_params
    params.permit(:code, :provider)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:session][:email], params[:session][:password])
      flash[:success] = 'Login successful'
      redirect_back_or_to root_path
    else
      flash.now[:warning] = 'Login failed'
      render new_user_session_path
    end
  end

  def destroy
    logout
    redirect_to root_path, flash: { success: 'Logged out!' }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to root_path, flash: { success: 'Пользователь обновлен' }
    else
      flash.now[:warning] = 'Ошибка'
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login @user
      redirect_to root_path, flash: { success: 'User was successfully created' }
    else
      render new_user_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :locale)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_locale(locale)
    I18n.locale == locale
  end
end

app/views/cards/_form.html.slim
- if @decks.any?
  - if @card.card_image?
    .thumbnail
      img src="#{@card.card_image.url}" alr=""
      
  = simple_form_for @card do |f|
    = f.error_notification
    = f.hidden_field :user_id, value: current_user.id
    = f.input :original_text
    = f.input :translated_text
    .form-group.string.required.card_image
      label.string.required.control-label for="card_image" Card image
      = f.file_field :card_image, id: 'card_image'
    - if action_name == 'edit'
      = f.input :review_date, default: Time.zone.now
    = f.input :deck_id, collection: @decks, include_blank: false
    = f.button :submit
    
- else
  p.bg-info 
    p Сначала создайте хотя-бы одну колоду
    = link_to 'создать колоду', new_deck_path

app/views/cards/_revision.html.slim
.form
  h3 = card.translated_text
  .thumbnail
    img src="#{card.card_image.url}" alt=""
  = simple_form_for card, url: revision_card_path, method: "post" do |f|
    = f.hidden_field :id, value: card.id
    = text_field_tag :answer, 
      nil,
      autocomplete: "off",
      placeholder: "Перевод",
      class: "form-control"
    br
    = f.button :submit, value: "Проверить"

app/views/cards/_right_answer.html.slim
h3 = @card.translated_text
hr
p Правильный ответ: #{ @card.original_text }
p Ваш ответ: #{ @answer }
hr
= link_to 'Следующая карта', root_path

app/views/cards/edit.html.slim
h3 Редактор карточки

.form
  = render partial: "form"

app/views/cards/index.html.slim
- if @cards.blank?
  .alert.alert-info.text-center Карточки еще не завезли!
- else
  .row
    - @cards.each do |card|
      .col-md-3.col-sm-4.col-xs-6
        .card
          = link_to "удалить", card, method: :delete, data: { confirm: 'Удаляем?' }, class: "card_delete"
          .card_date = card.review_date
          .card_original = card.original_text
          .card_translate = card.translated_text
          = link_to "редактировать", edit_card_path(card), class: "card_edit"
          
          

app/views/cards/new.html.slim
h3 Новая карточка

.form
  = render partial: "form"

app/views/common/_flash_noty.html.slim
- if flash.any?
  = flash
  .noty
    - flash.each do |key, value|
      div class="alert alert-#{key}"
        = value

app/views/common/_navbar.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#navbar-collapse" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Флэшкарточкер", root_path, class: "navbar-brand"
    
    .collapse.navbar-collapse#navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if !current_user
          li class=('active' if current_locale(:en))
            = link_to 'EN', locale: 'en'
          li class=('active' if current_locale(:ru))
            = link_to 'RU', locale: 'ru'
        - if logged_in?
          li.dropdown
            a#dropuser.dropdown-toggle data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              = current_user.email
              span.caret 
            ul.dropdown-menu aria-labelledby="dropuser"
              li = link_to t('all_cards'), cards_path
              li = link_to t('all_decks'), decks_path
              li.divider role="seperator"
              li = link_to t('create_card'), new_card_path
              li = link_to t('create_deck'), new_deck_path
              li.divider role="seperator"
              li = link_to t('profile'), edit_user_path(current_user.id)
              li = link_to t('exit'), logout_path, :method => :post
        - else
          li = link_to t('sign_up'), new_user_path
          li = link_to t('sign_in'), login_path
          li = link_to t('sign_in_facebook'), auth_at_provider_path(:provider => :facebook)  

app/views/decks/_form.html.slim
= simple_form_for deck do |f|
  = f.error_notification
  = f.hidden_field :user_id, value: current_user.id
  = f.input :title
  = f.input :current, wrapper: :vertical_radio_and_checkboxes
  = f.button :submit

app/views/decks/edit.html.slim
h1 Редактирование колоды

= render partial: 'form', locals: { deck: @deck }

br 

= link_to "удалить", @deck, method: :delete, data: { confirm: 'Удаляем?' }

app/views/decks/index.html.slim
- if @decks.any?
  h1 Ваши колоды
  
  ul
    - @decks.each do |deck|
      li 
        p class="#{ 'bg-success' if deck.current }" = link_to deck.title, deck_path(deck.id)      
- else
  .alert.alert-info.text-center Колоды еще не завезли!

app/views/decks/new.html.slim
h1 Новая колода

= render partial: 'form', locals: { deck: @deck }

app/views/decks/show.html.slim
h1 = @deck.title
= link_to 'Редактировать', edit_deck_path
hr
- if @deck.cards.any?
  
  - @deck.cards.each do |card|
    .col-md-3.col-sm-4.col-xs-6
      .card
        = link_to "удалить", card, method: :delete, data: { confirm: 'Удаляем?' }, class: "card_delete"
        .card_date = card.review_date.strftime("%d/%m/%Y") 
        .card_original = card.original_text
        .card_translate = card.translated_text
        = link_to "редактировать", edit_card_path(card), class: "card_edit"
  
- else
  h3 нету карточек
  = link_to 'Добавить карточку', new_card_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title FlashManager
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'common/flash_noty'
    = render 'common/navbar'
    .container.main-container
      = yield

app/views/main/index.html.slim
- if @revision_card
  = render partial: "cards/revision", locals: { card: @revision_card }
  br
  p = link_to "Другое слово", root_path, class: "btn btn-default"
- else
  h3 Карточки кончились

app/views/oauths/callback.html.slim
h1 Oauths#callback
p Find me in app/views/oauths/callback.html.slim

app/views/oauths/oauth.html.slim
h1 Oauths#oauth
p Find me in app/views/oauths/oauth.html.slim

app/views/user_sessions/_form.html.slim
= simple_form_for :session, { url: user_sessions_path, method: :post }  do |f|
  = f.error_notification
  = f.input :email
  = f.input :password
  = f.button :submit, "Войти"

app/views/user_sessions/new.html.slim
h1 Login

= render partial: 'form', locals: { user: @user }

app/views/users/_form.html.slim
.form
  = simple_form_for user do |f|
    = f.error_notification
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
    = f.input :locale, collection: I18n.available_locales
    = f.button :submit

app/views/users/edit.html.slim
h1 Edit user
= render partial: 'form', locals: { user: @user }

app/views/users/new.html.slim
= render partial: 'form', locals: { user: @user }